name: fs_service

packages:
  - '.'
#  - '*'
#  - '**'

scripts:
  analyze:
    description: "Analyze sources"
    run: |
      dart run melos exec --concurrency=1 --\
        flutter analyze

  check:
    description: "Check format, analyze, test and show coverage percent"
    run: |
      dart run melos exec --concurrency=1 --\
        dart run melos run format:check && \
        dart run melos run analyze && \
        dart run melos run test && \
        dart run melos run coverage:check

  coverage:
    description: "Show coverage in the default browser"
    run: |
      dart run melos run coverage:filter && \
      dart run melos run coverage:html && \
      open coverage/html/index.html

  coverage:check:
    description: "Check coverage is more that some threshold"
    packageFilters:
      dirExists:
        - test
    run: |
      dart run melos exec --concurrency=1 --\
        dart pub global activate check_coverage && \
        cat coverage/lcov.info | check_coverage 75

  coverage:filter:
    description: "Filter coverage"
    run: |
      mv -f coverage/lcov.info coverage/lcov-all.info && \
      lcov --ignore-errors unused \
        --remove coverage/lcov-all.info \
        '*.g.dart' '*.freezed.dart' \
        -o coverage/lcov.info && \
      rm -f coverage/lcov-all.info

  coverage:html:
    description: "Generate coverage html"
    run: |
      genhtml coverage/lcov.info -o coverage/html

  fix:
    description: "Apply dart fix"
    run: |
      dart run melos exec --concurrency=1 --\
        dart fix --apply

  format:
    description: "Format all sources"
    run: |
      dart run melos exec --\
        dart format .

  format:check:
    description: "Check if all sources are formatted"
    run: |
      dart run melos exec --concurrency=1 --\
        dart format --set-exit-if-changed .

  test:
    description: "Run tests with coverage"
    packageFilters:
      dirExists:
        - test
    run: |
      dart run melos exec --concurrency=1 --\
        flutter test --coverage -j 1 .

  upgrade:
    description: "Upgrade packages"
    run: |
      dart run melos exec --concurrency=1 --\
        dart pub upgrade --major-versions

  publish:
    description: "Publish to pub.dev"
    run: |
      dart run melos exec --concurrency=1 --\
        dart pub publish --force
